config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :medicaments
  get 'medicament/:id/increment', to: 'medicaments#increment', as: 'increment_medicament'
  get 'medicament/:id/decrement', to: 'medicaments#decrement', as: 'decrement_medicament'
  get '/profil', to: 'dashboards#profil', as: "profil"
  delete '/profil/medical_cares/:id', to: 'medical_cares#destroy', as: 'delete_medical_care'
  delete '/appointments/:id', to: 'appointments#destroy', as: 'delete_appointment'
  delete '/profil/medical_cares/:medical_care_id/medical_care_medicaments/:id', to: 'medical_care_medicaments#destroy', as: 'delete_medical_care_medicament'
  resources :profil do
    collection do
      resources :medical_cares do
        resources :medical_care_medicaments do
          get :taken
        end
      end
    end
  end
  resources :medical_centers, only: [:index] do
    resources :appointments, except: [:show]
  end
  resources :appointments, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/views/pages/home.html.erb
<div class="container-home">

  <div>
    <div class="barre-separation-accueil"></div>
      <h5>Calendrier</h5>
    <div class="barre-separation-accueil"></div>
  </div>

  <div class="calendar-container">
  <div class="calendar-row date-name" style="gap: 8px;">
    <%(0..6).each do |day| %>
      <% jour = Date.today + day.day %>
      <p><%= translate_day(jour.strftime("%a")).capitalize %></p>
    <% end %>
  </div>
      <% (0..13).each do |i| %>
        <% date = (Date.today + i.day).strftime %>
        <% if i % 7 == 0 %>
          <div class="calendar-row">
        <% end %>
        <% if date == params[:date] %>
          <div class="date-day">
        <% else %>
          <div class="empty-week-day">
        <% end %>
        <%= link_to request.params.merge(date: date ) do %>
          <%= week_day = Date.parse(date).strftime("%d") %>
        <% end %>
        </div>
        <% if i % 7 == 6 || i == 13 %>
          </div>
        <% end %>
      <% end %>
  </div>

  <div>
  <div class="barre-separation-accueil"></div>
    <h5>Prises du jour</h5>
  <div class="barre-separation-accueil"></div>
  </div>


    <% @traitements.each do |traitement| %>
    <div class="patient-home">
      <p><%= traitement.title %></p>
        <% traitement.medical_care_medicaments.each do |traitement_medicament| %>
        <div class="barre-separation-accueil-int"></div>

          <div class="medicament-name">
            <%= traitement_medicament.medicament.name %> <br>
          </div>
          <div class="medicament-dose">
            <%= traitement_medicament.dose.to_i %>
            <%= "#{traitement_medicament.medicament.unit.pluralize} / jour" %> <br>
            <% if dose(traitement_medicament) != "" %>
            <div class="btn-medicament-prit">
            <%= link_to medical_care_medical_care_medicament_taken_path(traitement.id, traitement_medicament.id, taken: { symb_for_mcm.to_sym => true }) do %>
    Prendre
<% end %>

          </div>
          <% else %>
          <div class="pris-text">
            <p id="medicament-pris"><%= "Medicament pris" %></p>
          </div>
          <% end %>
        </div>
        <% end %>
    </div>
      <% end %>
  <div class="barre-separation-accueil", id="barre-accueil-rdv-haut"></div>
  <h5>Rendez-vous du jour</h5>
  <div class="barre-separation-accueil", id="barre-accueil-rdv-bas"></div>

    <% @appointments.each do |appointment| %>
    <div class="rdv-home">
        <div class="rdv-home-info">
          <div class="nom-adresse-rdv-home">
            <%= appointment.medical_center.name %> <br>
            <%= appointment.medical_center.address %> <br>
          </div>
          <div class="date-rdv-home">
            <%= translate_day(appointment.date.strftime("%A")) + " " + appointment.date.strftime("%d") + " " + translate_month(appointment.date.strftime("%B")) + " " + appointment.date.strftime("%H:%M")  %>
          </div>
        </div>
    </div>
    <% end %>
</div>

<%# Footer %>

<div class="footer-container">
  <div class="footer-button active-footer">
    <%= link_to root_path do %>
      <%= image_tag("footer-a-accueil.svg", alt: "Accueil") %>
    <% end %>
  </div>

  <div class="footer-button">
    <%= link_to medical_centers_path do %>
      <%= image_tag("footer-centres.svg", alt: "Centres Médicaux") %>
    <% end %>
  </div>

  <div class="footer-button">
    <%= link_to medicaments_path do %>
      <%= image_tag("footer-medicaments.svg", alt: "Médicaments") %>
    <% end %>
  </div>
</div>
<div class="espace-vide-footer"></div>

<%# Footer %>