config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :medicaments
  get 'medicament/:id/increment', to: 'medicaments#increment', as: 'increment_medicament'
  get 'medicament/:id/decrement', to: 'medicaments#decrement', as: 'decrement_medicament'
  get '/profil', to: 'dashboards#profil', as: "profil"
  delete '/profil/medical_cares/:id', to: 'medical_cares#destroy', as: 'delete_medical_care'
  delete '/appointments/:id', to: 'appointments#destroy', as: 'delete_appointment'
  delete '/profil/medical_cares/:medical_care_id/medical_care_medicaments/:id', to: 'medical_care_medicaments#destroy', as: 'delete_medical_care_medicament'
  resources :profil do
    collection do
      resources :medical_cares do
        resources :medical_care_medicaments do
          get :taken
        end
      end
    end
  end
  resources :medical_centers, only: [:index] do
    resources :appointments, except: [:show]
  end
  resources :appointments, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/medical_center.rb
class MedicalCenter < ApplicationRecord
  has_many :appointments
end

app/controllers/medical_centers_controller.rb
class MedicalCentersController < ApplicationController
  def index
    @title = "Nouveau RDV"
    @medical_centers = MedicalCenter.all
  end
end

app/views/medical_centers/index.html.erb
<div class="prise-rdv-container">

  <div class="barre-separation-rdv-prise-top"></div>

  <div class="texte-labos"><p>Laboratoires à proximité</p></div>

  <div id="barre-separation-bot"></div>

  <% @medical_centers.each do |medical_center| %>
    <div class="carte-prise-rdv">

      <div class="titre-centre-rdv">
        <h5><%= medical_center.name %></h5>
      </div>

      <div class="adresse-centre-rdv">
        <p><%= medical_center.address %></p>
      </div>

      <div class="flex-container-rdv">

        <div class="tel-centre-rdv">
          <p>Tél: <%= medical_center.phone_number %></p>
        </div>
        <div class="btn-ajouter-a-mes-rdv">
          <%= link_to "Ajouter à mes RDV", new_medical_center_appointment_path(medical_center.id) %>
        </div>
      </div>


    </div>
  <% end %>

  <div class="barre-separation-rdv-prise"></div>

  <div class="section-btn-mes-rdv">
    <div class="btn-mes-rdv">
      <%= link_to "Mes RDV", appointments_path%>
    </div>
  </div>

</div>

<%# Footer %>

<div class="footer-container">
  <div class="footer-button">
    <%= link_to root_path do %>
      <%= image_tag("footer-accueil.svg", alt: "Accueil") %>
    <% end %>
  </div>

  <div class="footer-button active-footer">
    <%= link_to medical_centers_path do %>
      <%= image_tag("footer-a-centres.svg", alt: "Centres Médicaux") %>
    <% end %>
  </div>

  <div class="footer-button">
    <%= link_to medicaments_path do %>
      <%= image_tag("footer-medicaments.svg", alt: "Médicaments") %>
    <% end %>
  </div>
</div>
<div class="espace-vide-footer"></div>

<%# Footer %>