config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :medicaments
  get 'medicament/:id/increment', to: 'medicaments#increment', as: 'increment_medicament'
  get 'medicament/:id/decrement', to: 'medicaments#decrement', as: 'decrement_medicament'
  get '/profil', to: 'dashboards#profil', as: "profil"
  delete '/profil/medical_cares/:id', to: 'medical_cares#destroy', as: 'delete_medical_care'
  delete '/appointments/:id', to: 'appointments#destroy', as: 'delete_appointment'
  delete '/profil/medical_cares/:medical_care_id/medical_care_medicaments/:id', to: 'medical_care_medicaments#destroy', as: 'delete_medical_care_medicament'
  resources :profil do
    collection do
      resources :medical_cares do
        resources :medical_care_medicaments do
          get :taken
        end
      end
    end
  end
  resources :medical_centers, only: [:index] do
    resources :appointments, except: [:show]
  end
  resources :appointments, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def profil
    @medical_care_medicament = MedicalCareMedicament.all
    @medical_cares = MedicalCare.all
  end
end

app/views/dashboards/profil.html.erb
<div class="container-profil">
  <div class="navbar-profil-dash">
    <div class="navbar-profil-dash-left">
      <%# <%= link_to image_tag("Icon-barre-options.svg", alt: "Bouton gauche"), "#" %>
    </div>
    <div class="navbar-profil-dash-title">
      <h1>Tableau de bord</h1>
    </div>
    <div class="navbar-profil-dash-right">
      <%= link_to image_tag("icon-barre-fermer.svg", alt: "Bouton droit"), root_path %>
    </div>
  </div>
  <div class="barre-separation-profil"></div>
  <div class="titre-mes-patients">
    <h5>Mes Patients</h5>
  </div>
    <% current_user.medical_cares.each do |traitement| %>
    <div class="mes-patients">
      <div class="patient-unique">
        <div class="title">
          <h5><%= traitement.title %></h5>
          <p><%= traitement.description %></p>
        </div>
          <div class="traitement-date">
            <div class="start-date card">
              <div class="debut-fin-du-traitement-texte">
                <p>Début du traitement :
              </div>
              <div>
                <em><%= translate_day(traitement.start_date.strftime("%A")) %></em>
                <em><%= traitement.start_date.strftime("%d") %></em>
                <em><%= translate_month(traitement.start_date.strftime("%B")) %></em>
                <div>
                  <em><p><%= traitement.start_date.strftime("%Y")%></p></em>
                </div>
              </div>
            </div>
          <div class="end-date card">
            <div class="debut-fin-du-traitement-texte">
              <p>Fin du traitement :
            </div>
            <div>
              <em><%= translate_day(traitement.end_date.strftime("%A")) %></em>
                <em><%= traitement.end_date.strftime("%d") %></em>
                <em><%= translate_month(traitement.end_date.strftime("%B")) %></em>
                <div>
                  <em><%= traitement.end_date.strftime("%Y")%></p></em>
                </div>
            </div>
          </div>
        </div>
        <div class="barre-separation-profil-int"></div>
        <div>
        </div>
        <% traitement.medical_care_medicaments.each do |traitement_medicament| %>
          <div class="medicament-container">
            <div>
              <h5><%= "#{traitement_medicament.medicament.name.upcase}" %></h5>
              <p><%= traitement_medicament.dose.to_i %>
              <%= traitement_medicament.medicament.unit.pluralize %></p>
            </div>
            <div class="btn-supprimer-medicament">
              <%= link_to image_tag("supprimer_ico.svg"), delete_medical_care_medicament_path(traitement.id, traitement_medicament.id), data: {turbo_method: :delete} %>
            </div>
          </div>
        <% end %>

        <div class="barre-separation-profil-int"></div>

      </div>

        <div class="ajout-medicament">
          <%= link_to "Ajouter un medicament", new_medical_care_medical_care_medicament_path(traitement.id), class: "btn-ajout-medicament"  %>
        </div>

        <div class="section-btn-editer-traitement">
          <%= link_to "Editer", edit_medical_care_path(traitement.id), class: "btn-editer-traitement" %>
        </div>
        <div class="section-btn-supprimer-traitement">
          <%= link_to "Supprimer", delete_medical_care_path(traitement.id), data: {turbo_method: :delete}, class: "btn-supprimer-traitement"   %>
        </div>
        </div>
    <% end %>
</div>
<div class="ajout-patient">
  <%= link_to "Ajouter un patient", new_medical_care_path, class: "btn-ajout-patient-bas" %>
</div>