config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :medicaments
  get 'medicament/:id/increment', to: 'medicaments#increment', as: 'increment_medicament'
  get 'medicament/:id/decrement', to: 'medicaments#decrement', as: 'decrement_medicament'
  get '/profil', to: 'dashboards#profil', as: "profil"
  delete '/profil/medical_cares/:id', to: 'medical_cares#destroy', as: 'delete_medical_care'
  delete '/appointments/:id', to: 'appointments#destroy', as: 'delete_appointment'
  delete '/profil/medical_cares/:medical_care_id/medical_care_medicaments/:id', to: 'medical_care_medicaments#destroy', as: 'delete_medical_care_medicament'
  resources :profil do
    collection do
      resources :medical_cares do
        resources :medical_care_medicaments do
          get :taken
        end
      end
    end
  end
  resources :medical_centers, only: [:index] do
    resources :appointments, except: [:show]
  end
  resources :appointments, only: [:index, :new, :create, :edit, :update, :destroy]
end

app/models/medicament.rb
class Medicament < ApplicationRecord
  has_many :medical_care_medicaments, through: :medical_care
  UNITS = ["Comprimé", "Gellule", "Pommade", "Poudre", "Suppositoire", "Gouttes"]
  attr_accessor :increment_value
end

app/controllers/medicaments_controller.rb
class MedicamentsController < ApplicationController
  before_action :set_medicament, only: [:show, :edit, :update]

  def index
    @title = "Médicaments"
    @medicaments = Medicament.all
    @medicaments = Medicament.order(:id)
    @medicament = Medicament.new
  end

  def show
  end

  def new
    @medicament = Medicament.new
  end

  def create
    @medicament = Medicament.new(medicament_params)
    if @medicament.save
      redirect_to medicaments_path, notice: "Le médicament a été ajouté avec succès."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @medicament.update(medicament_params)
      redirect_to medicament_path(@medicament), notice: "Le médicament a été mis à jour avec succès."
    else
      render :edit
    end
  end

  def increment
    @medicament = Medicament.find(params[:id])
    @medicament.increment!(:stock)
    @medicament.save!
    respond_to do |format|
      format.html { redirect_to medicaments_path }
      format.json { head :no_content }
    end
  end

  def decrement
    @medicament = Medicament.find(params[:id])
    @medicament.decrement!(:stock)
    @medicament.save!
    respond_to do |format|
      format.html { redirect_to medicaments_path }
      format.json { head :no_content }
    end
  end

  private

  def set_medicament
    @medicament = Medicament.find(params[:id])
  end

  def medicament_params
    params.require(:medicament).permit(:name, :unit, :stock)
  end
end
#   def show
#     @medicament = Medicament.find(params[:id])
#   end

#   def new
#     @medicament = Medicament.new
#   end

#   def create

#   end

#   def edit
#     @medicament = Medicament.find(params[:id])
#   end

#   def update
#     @medicament = Medicament.find(params[:id])
#     @stock_medicament = @medicament.stock
#     if @medicament.update(medicament_params)
#       redirect_to medicaments_path
#     else
#       # render: :edit
#   end

#   private

#   def medicament_params
#     params.require(:medicament).permit(:stock)
#   end
# end

app/views/medicaments/edit.html.erb
<h1>Modifier votre stock de médicaments</h1>

<div>
  <%= simple_form_for @medicament do |f| %>
    <%= f.input :increment_value, required: true %>
    <%= f.submit "Modifier le stock", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/medicaments/index.html.erb
<div class="container-medicaments">
  <div class="barre-separation-medicament"></div>
  <div class="titre-stock-actuel"><p>Stock actuel</p></div>
  <div class="barre-separation-medicament" id="barre2"></div>

    <tbody class="tableau-medicaments">
      <div class="medicaments-card">
        <% @medicaments.each do |medicament| %>
          <div class="info-medicaments">

              <div class="medicament-nom">
                <td><%= medicament.name.upcase %></td>
              </div>

              <div class="moins-quantite-plus">
                <div class="btn-moins">
                  <td><%= link_to image_tag("Icone-moins.svg"), decrement_medicament_path(medicament), remote: true %></td>
                </div>

                <div class="stock-chiffre">
                  <td><%= medicament.stock %></td>
                </div>

                <div class="btn-plus">
                  <td><%= link_to image_tag("Icone-plus.svg"), increment_medicament_path(medicament), remote: true %></td>
                </div>
              </div>

          </div>

        <% end %>
      </div>
    </tbody>

  <div class="ajouter-medicament">
    <div class="barre-separation-medicament", id="barre2"></div>
    <div class="titre-stock-actuel"><p>Ajouter un médicament</p></div>
    <div class="barre-separation-medicament", id="barre3"></div>
          <%= form_with model: @medicament, url: medicaments_path, method: :post do |form| %>
            <div class="form">
              <div class="form-name">
                <div class="label-left">
                  <%= form.label :name, "Nom" %>
                </div>
                <div class="form-select-input">
                  <%= form.text_field :name %>
                </div>
              </div>
              <div class="form-stock">
                <div class="label-left">
                  <%= form.label :stock, "Stock" %>
                </div>
                <div class="form-select-input">
                  <%= form.text_field :stock %>
                </div>
              </div>
              <div class="form-unit">
                <div class="label-left">
                  <%= form.label :unit, "Type" %>
                </div>
                <div class="form-select-input">
                  <%= form.select :unit, Medicament::UNITS %>
                </div>
              </div>
              <div class="ajouter-medicament" id="ajouter-medicament-btn">
                <%= form.submit "Ajouter", id:"ajouter-medicament-btn" %>
              </div>
            </div>
            <% end %>
  </div>
</div>

<%# Footer %>

<div class="footer-container">
  <div class="footer-button">
    <%= link_to root_path do %>
      <%= image_tag("footer-accueil.svg", alt: "Accueil") %>
    <% end %>
  </div>

  <div class="footer-button">
    <%= link_to medical_centers_path do %>
      <%= image_tag("footer-centres.svg", alt: "Centres Médicaux") %>
    <% end %>
  </div>

  <div class="footer-button active-footer">
    <%= link_to medicaments_path do %>
      <%= image_tag("footer-a-medicaments.svg", alt: "Médicaments") %>
    <% end %>
  </div>
</div>
<div class="espace-vide-footer"></div>

<%# Footer %>